### ISSUE TITLE
Next up

### ISSUE THREAD

**Issue by oskarrough** [radio4000/blog#1]
Some thoughts…

- How would we like our URL structure for each blog post to be?
- I made taxonomy pages ([example](https://radio4000-blog.netlify.com/tags/feature/)) but do we want them? It's a tiny bit fun.
- Change DNS
- Images are served from Tumblr. How do we deal with the Tumblr blog?
- I very roughly checked the exported markdown but it could probably use some trimming

**Comment by 4www** [comment]
Ahhhh, images...

Also images could be clickable, a link to the image itself.

**Comment by 4www** [comment]
We can also add `categories`.

I'm thinking that there are external contributors (loic, lucas...) willing to write articles about music, how it is shared etc., also very different content.

http://github.com/internet4000/publications/

**Comment by oskarrough** [comment]
Pushed local images in https://github.com/internet4000/radio4000-blog/commit/1f1a5f1cba4b06ff83c321caab4caa3da1a3082d.

Author is cool, probably already supported by hugo?

**Comment by 4www** [comment]
I don't have author in mind, just categories.

**Comment by oskarrough** [comment]
Alright, as this is now online and images are moved, we can open another issue for tags and categories if we want.
